using Halo.Launcher;

namespace Halo.Tests;

// Every case here is a real line from --probe-apps on a live machine, not an invented one: 270 raw
// entries, 28 of them documents or links and 2 of them uninstallers.
public sealed class AppScanTests
{
    [Theory]
    [InlineData("Uninstall Node.js", "Microsoft.AutoGenerated.{11949A8A-59A2-8DA5-CD1F-3FD60D029673}")]
    [InlineData("Uninstall Counter-Strike Global Offensive", @"D:\csgo-2\unins000.exe")]
    public void Uninstallers_NeedTheNameBecauseTheTargetDoesNotGiveThemAway(string name, string target)
    {
        // one is a bare AutoGenerated GUID and the other is an ordinary .exe - nothing structural to
        // catch, which is why the name rule exists alongside the target rule
        Assert.True(AppScan.IsJunk(name, target));
    }

    [Theory]
    [InlineData("Removed Files Recovery", @"C:\Program Files\Recovery\rec.exe")]
    [InlineData("Remover", @"C:\Program Files\Remover\remover.exe")]
    [InlineData("Uninstaller Deluxe", @"C:\Program Files\Unin\unin.exe")]
    public void NamesThatOnlyLookLikeUninstallers_Survive(string name, string target)
    {
        // the prefixes carry their trailing space and underscore for exactly this: "Removed Files
        // Recovery" is not "Remove ", and "Uninstaller Deluxe" is not "Uninstall "
        Assert.False(AppScan.IsJunk(name, target));
    }

    [Fact]
    public void AGenuineAppNamedUninstallSomething_IsCaught_AndThatIsAcceptedNotFixed()
    {
        // CrystalIdea's "Uninstall Tool" is a real product and this rule would hide it. The alternative
        // was inspecting the target, which for "Uninstall Node.js" is a bare AutoGenerated GUID that says
        // nothing. Two uninstallers removed from every user's results against one app hidden from the
        // few who own it: the trade is deliberate, and this test exists so it stays deliberate.
        Assert.True(AppScan.IsJunk("Uninstall Tool", @"C:\Program Files\Uninstall Tool\uninstalltool.exe"));
    }

    [Theory]
    [InlineData("Inno Setup Documentation", @"C:\Program Files\Inno Setup 6\ISetup.chm")]
    [InlineData("Inno Setup FAQ", @"C:\Program Files\Inno Setup 6\isfaq.url")]
    [InlineData("Inno Setup Revision History", @"C:\Program Files\Inno Setup 6\whatsnew.htm")]
    [InlineData("Python 3.13 Manuals (64-bit)", @"C:\Python313\Doc\html\index.html")]
    [InlineData("User manual (PDF, English)", @"C:\Oracle\VirtualBox\doc\UserManual.pdf")]
    [InlineData("License (English)", @"C:\Oracle\VirtualBox\License_en_US.rtf")]
    [InlineData("Console RAR manual", @"C:\WinRAR\Rar.txt")]
    [InlineData("Node.js website", "https://nodejs.org/")]
    [InlineData("Steam Support Center", "http://support.steampowered.com/")]
    public void DocumentsAndLinks_AreNotApps(string name, string target)
    {
        Assert.True(AppScan.IsJunk(name, target));
    }

    [Theory]
    [InlineData("Telegram", @"C:\Users\x\AppData\Roaming\Telegram Desktop\Telegram.exe")]
    [InlineData("Notepad", "Microsoft.WindowsNotepad_8wekyb3d8bbwe!App")]
    [InlineData("Windows Terminal", "Microsoft.WindowsTerminal_8wekyb3d8bbwe!App")]
    [InlineData("VLC media player", @"C:\Program Files\VideoLAN\VLC\vlc.exe")]
    [InlineData("Install Additional Tools for Node.js", "Microsoft.AutoGenerated.{04770C2D-34E6}")]
    public void RealApps_Survive(string name, string target)
    {
        // the AutoGenerated one is arguably junk too, but it is structurally identical to entries that
        // are not - so it stays, and the ranking puts it below the app it shares a prefix with
        Assert.False(AppScan.IsJunk(name, target));
    }

    [Theory]
    [InlineData("", "something.exe")]
    [InlineData("   ", "something.exe")]
    [InlineData("Named", "")]
    public void BlankEitherSide_IsJunk(string name, string target)
    {
        Assert.True(AppScan.IsJunk(name, target));
    }

    [Fact]
    public void AnExeWhoseFolderLooksLikeADocument_Survives()
    {
        // the check is on the END of the target, not on it containing a word - a real trap for anyone
        // who reaches for Contains() here
        Assert.False(AppScan.IsJunk("Reader", @"C:\Program Files\docs.url.company\reader.exe"));
    }
}
